name: Build Antora docs

on:
  workflow_call:
    inputs:
      profile:
        description: 'Project profile'
        required: true
        type: string
      version:
        description: 'Project version'
        required: true
        type: string
      hashVersion:
        description: 'Project hash commit'
        required: true
        type: string
      sha:
        description: 'SHA commit id'
        required: true
        type: string
      isRelease:
        description: 'Is release'
        default: 'false'
        required: false
        type: string
      antoraBuildDir:
        description: 'Specifics Antora output dir per profile'
        required: false
        type: string
      docBranch:
        description: 'Doc branch'
        required: true
        type: string
      docVersion:
        description: 'Doc version'
        required: true
        type: string
      docCommitMsg:
        description: 'Doc commit message'
        required: true
        type: string
      javaVersion:
        description: 'Java version'
        default: '17'
        required: false
        type: string
    secrets:
      githubToken:
        description: 'GitHub Token'
        required: true
      gpgKey:
        description: 'GPG private key'
        required: true
      gpgPassphrase:
        description: 'GPG passphrase'
        required: true
      gpgFingerprint:
        description: 'GPG subkey fingerprint'
        required: false
        
env: 
  JAVA_DIST: 'temurin'

jobs:
  build-docs:
    name: Build Antora ${{ inputs.profile }} documentation
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ inputs.profile }}
      PROJECT_DOCS_REF: docs/main
      PROJECT_DOCS_PATH: ${{ inputs.profile }}-docs
      DOC_PROFILE: ${{ inputs.profile }}:docs
      DOC_PROFILE_PATH: antora/${{ inputs.profile }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
          submodules: 'true'
          
      - name: Checkout ${{ env.PROJECT_NAME }} ${{ env.PROJECT_DOCS_REF }}
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PROJECT_DOCS_REF }}
          path: ${{ env.PROJECT_DOCS_PATH }}
          token: ${{ secrets.githubToken }}
          
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: false
          git_push_gpgsign: false
          gpg_private_key: ${{ secrets.gpgKey }}
          passphrase: ${{ secrets.gpgPassphrase }}
          fingerprint: ${{ secrets.gpgFingerprint }}
          workdir: ${{ env.PROJECT_DOCS_PATH }}

      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ inputs.javaVersion }}
          cache: 'gradle'

      - name: Build docs
        shell: bash
        run: |
          ./gradlew antoraDoc \
              -Pprofile=${{ env.DOC_PROFILE }} \
              -PdocVersion=${{ inputs.docVersion }} \
              -Pversion=${{ inputs.version }} \
              -PbuildHash=${{ inputs.hashVersion }} \
              -PbuildBy="GitHub-Action"

      - name: Sync doc output to Git branch [${{ inputs.docBranch }}]
        shell: bash
        run: |
          fqn_doc_path="${{ env.PROJECT_DOCS_PATH }}/${{ env.DOC_PROFILE_PATH }}"
          rm -rf $fqn_doc_path \
            && mkdir $fqn_doc_path \
            && touch $fqn_doc_path/.gitkeep \
            && cp -rf ./${{ inputs.antoraBuildDir }}/* $fqn_doc_path
          cd ${{ env.PROJECT_DOCS_PATH }}
          git add .
          git diff-index --quiet HEAD || git commit -am "Update ${{ inputs.docCommitMsg }}"
          if [[ '${{ inputs.isRelease }}' == 'true' ]]; then
               git tag -sf -am "Release ${{ inputs.docCommitMsg }}" ${{ inputs.docBranch }}
          fi
          git push -u origin ${{ inputs.docBranch }}
