name: Project Build

on:
  workflow_call:
    inputs:
      profile:
        description: 'Build profile'
        type: string
        required: true
      version:
        description: 'Project version'
        type: string
        required: true
      semanticVersion:
        description: 'Project semantic version'
        type: string
        required: true
      hashVersion:
        description: 'Project hash commit'
        type: string
        required: true
      buildArgs:
        description: 'Gradle build arguments'
        required: false
        type: string
        default: 'clean build'
      javaDist:
        description: 'Java distribution'
        required: false
        type: string
        default: 'temurin'
      javaVersion:
        description: 'Java version'
        required: false
        type: string
        default: '11'
      runnerOS:
        description: 'Runner OS'
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  build:
    name: Run "${{ inputs.profile }}::${{ inputs.buildArgs }}"
    runs-on: ${{ inputs.runnerOS }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.javaDist }}
          java-version: ${{ inputs.javaVersion }}

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v') }}

      - shell: bash
        name: Run "${{ inputs.buildArgs }}"
        run: |
          ./gradlew ${{ inputs.buildArgs }} \
              -Pprofile=${{ inputs.profile }} \
              -Pversion=${{ inputs.version }} \
              -PsemanticVersion=${{ inputs.semanticVersion }} \
              -PbuildBy="GitHub-Action" \
              -PbuildHash=${{ inputs.hashVersion }} \
              --no-daemon
