name: Deploy webdocs on shared repository

on:
  workflow_call:
    inputs:
      webdocsRepo:
        description: 'Webdocs repository'
        required: true
        type: string
      webdocsRef:
        description: 'Webdocs ref'
        default: 'main'
        required: false
        type: string
      webdocsWorkflow:
        description: 'Webdocs workflow'
        default: 'webdocs.yml'
        required: false
        type: string
      docCommitMsg:
        description: 'CI message'
        required: true
        type: string
    secrets:
      githubToken:
        description: 'GitHub Token to trigger workflow on Webdocs repository'
        required: true

jobs:
  deploy-site:
    name: Trigger deploy webdocs
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.githubToken }}
    steps:
      - name: Trigger build ${{ inputs.profile }} documentation
        shell: bash
        run: |
          gh workflow run ${{ inputs.webdocsWorkflow }} \
            --repo ${{ inputs.webdocsRepo }} \ 
            --ref ${{ inputs.webdocsRef }} \
            -f docCommitMsg=${{ inputs.docCommitMsg }}

      - name: Verify GitHub workflow run
        shell: bash
        run: |
          sleep 5
          fields=workflowDatabaseId,databaseId,status,event,headBranch,headSha,name,conclusion,url,createdAt,updatedAt
          gh run list -R ${{ inputs.webdocsRepo }} -b ${{ inputs.webdocsRef }} -w ${{ inputs.webdocsWorkflow }} -L 1 --json $fields | jq
